### ISSUE TITLE
when to use the EventSource?

### ISSUE THREAD

**Issue by bhaidar** [oskardudycz/EventSourcing.NetCore#12]
Hello Oskar,
Is there a reason why you used EventSource as the base class with the Account domain model and not the Client?

Thanks

**Comment by oskardudycz** [comment]
Hi Bilal,

The main difference is that `Client` entity is not event sourced aggregate, but regular aggregate. It's also not stored in Marten but in regular tables through EntityFramework. I hade request to provide also example of CQRS written in EntityFramework. See more here:  see more here: https://github.com/oskardudycz/EventSourcing.NetCore/issues/6 In general it also shows that Marten and EntityFramework can go together without major issues. If you eg. need simple crud, or you have already existing system that you'd like to extend with Marten or other Event Store, then this sample shows how to do it.

In general EventSource is a base class for EventSourcing aggregates. It extends the `IAggregate` interface with the `PendingEvents` queue, that is used as a cache for the events that were created for exact aggregate in one scope/session. Then this queue is being used to publish events that were generated with business actions.

Is it now more clear? :)

**Comment by bhaidar** [comment]
Hello @oskardudycz 
Thanks a lot for your answer.

I am still new to CQRS and Event Sourcing. So to understand this better, when you say Event Sourced Aggregates, it means you care about recording the history of those entities by means of Event Sourcing? While Client entity is just using CQRS without Event Sourcing?

Going back to your sample, when handling commands for Client, you are still doing this:
`store.Append(@event.ClientId, @event);`

Doesn't that mean you are also storing "Events" in the "Store"?

**Comment by oskardudycz** [comment]
> I am still new to CQRS and Event Sourcing. So to understand this better, when you say Event Sourced Aggregates, it means you care about recording the history of those entities by means of Event Sourcing? While Client entity is just using CQRS without Event Sourcing?

Yes, that's correct. Of course if by saying `history` you mean all of the events that happened for those entity. In Event Sourcing entites are being stored as "stream of events". Which means that it's representation is it's `Id` (named also as stream Id) plus event's that happened for this entity. So when you're adding new entity then new stream will be created (in Marten stored in `mt_streams` table) and and event (eg. `AccountCreated` will be stored) in events table (in Marten they're stored in `mt_events`. Then they can be Aggregated again to get the current entity state. See more [here](https://github.com/oskardudycz/EventSourcing.NetCore/blob/master/Marten.Integration.Tests/EventStore/Aggregate/EventsAggregation.cs).

`store.Append(@event.ClientId, @event);` is used for getting events published in [ClientCommandHandler](https://github.com/oskardudycz/EventSourcing.NetCore/blob/d4a76a275262e86589a6e0e7e9804956391eb668/Sample/EventSourcing.Sample.Clients/Domain/Clients/Handlers/ClientsCommandHandler.cs) for storing those events in the store to be able to use it in the projections like this [one](https://github.com/oskardudycz/EventSourcing.NetCore/blob/d4a76a275262e86589a6e0e7e9804956391eb668/Sample/EventSourcing.Sample.Transactions/Views/Clients/ClientsViewProjection.cs) showing how to use together events from Accounts and Clients.

My general assumption was to show that Client entity doesn't have to publish any events etc., but looking at the code, I think that I a bit overcomplicated this sample. Client could also derive from the EventStore, because in fact then event it always creates event. I think that I'll update the sample.

**Comment by oskardudycz** [comment]
@bhaidar could you have a look on the https://github.com/oskardudycz/EventSourcing.NetCore/pull/14/files PR? I unified a bit EventSource. 

Main changes:
- renamed `EventSource`, to `EventSourcedAggregate`, imho the name is more descriptive. At the beginning `EventSource` was be more generic name, to say that it doesn't have to be Aggregate. But at the end that's just blurring and confusing. Now the name clearly states that it's Aggregate used for Event Sourcing. I added also `IEventSourcedAggregate` 

- Now the `Client` derives from this base class, and have simmilar usage as `Account `, so the event generation was moved from the command handler to aggregate method.

What do you think?

**Comment by dennisdoomen** [comment]
I like the separation between aggregates that are event sourced and those that are not. There's a lot of misconception about the scope of Event Sourcing and lot of folks still see it as a top-level architecture style.

**Comment by oskardudycz** [comment]
Closed, as there were no more comments.
